# letsencrypt-prod-cluster-issuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: encrypt-contacts
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: kamesh.pudi2014@hotmail.com
    privateKeySecretRef:
      name: encrypt-contacts
    solvers:
      - http01:
          ingress:
            class: nginx
